### ISSUE TITLE
[SDK] Expose better wrappers for pool liquidity operations

### ISSUE THREAD

**Issue by ChiTimesChi** [synapsecns/sanguine#1878]
# TODO
- [ ] Slippage adjustment for:
  - [ ] Adding liquidity to the pool
  - [ ] Removing liquidity from the pool in a balanced way
  - [ ] Removing liquidity from the pool in a form of a single token
- [ ] API for  populating the transaction:
  - [ ] Adding liquidity to the pool
  - [ ] Removing liquidity from the pool in a balanced way
  - [ ] Removing liquidity from the pool in a form of a single token
- [ ] The existing API for quotes is very confusing, needs to be changed
  - [ ] https://github.com/synapsecns/sanguine/blob/1b95502e029e6e14b588b5dff8a9c3ad0d4c76ec/packages/sdk-router/src/operations/pools.ts#L66-L71
  - [ ] https://github.com/synapsecns/sanguine/blob/1b95502e029e6e14b588b5dff8a9c3ad0d4c76ec/packages/sdk-router/src/operations/pools.ts#L102-L110
  - [ ] https://github.com/synapsecns/sanguine/blob/1b95502e029e6e14b588b5dff8a9c3ad0d4c76ec/packages/sdk-router/src/operations/pools.ts#L129-L138
