### ISSUE TITLE
RFQ/Submitter Fixes

### ISSUE THREAD

**Issue by trajan0x** [synapsecns/sanguine#2410]
- [x] Unstick existing in submitter: 0xdc unstuck. 0xdd optimism issues remain
- [x] Revert replace condition #2406 
- [x] Change default bump from 5->10% (min fee to replace an [existing transaction in geth](https://github.com/ethereum/go-ethereum/blob/8c5576b1ac89473c7ec15c9b03d1ca02e9499dcc/core/txpool/legacypool/legacypool.go#L146)): #2411
- [x] bump both priority fee and fee cap by max(current+10%, new suggested fee). New suggested fee calculated by (for london) [eth_gasPrice](https://github.com/ethereum/pm/issues/328#issuecomment-853234014) #2432
- [x] Start Fee cap lower than 10% and only bump by a minimum of 10% (on *both* priority fee and tip cap)
  <img width="987" alt="image" src="https://github.com/synapsecns/sanguine/assets/83933037/873f0e6d-e964-4b3f-9f2a-63d79ecd54d5"> #2432
- [x] Should not bump any transactions greater than the current pending nonce/submitting  #2432
- [x] Not bump above current gas balance #2420
- [x] Prometheus Metrics (pending count + longest pending)
- [x] Remove is_l2 as a config param #2442
- [x] Allow tx type to change in flight #2413 (is this actually working??)
- [x] Add a periodic garbage collector for old txes to prevent db bloat #2768
