### ISSUE TITLE
Omnirpc TODO

### ISSUE THREAD

**Issue by trajan0x** [synapsecns/sanguine#858]
There are a few things that have come up in production that would greatly improve the usability of omnirpc.

- [ ] Submit transactions to all endpoints
- [ ] RPC Types: Right now, all requests go through all endpoints. It would be nice to have a meter for this
- [ ] Better rate limiting (see: https://github.com/ethereum-optimism/optimism/tree/develop/proxyd)
- [ ] Definable max batch sizes per rpc endpoint and omnirpc level batch splitting
- [ ] Way to make a bath request across endpoints
- [ ] Metrics (Especially on latest block number of all chains)
- [ ] Better backoff support
